#!/bin/bash
### BEGIN INIT INFO
# Provides:          varlog
# Required-Start:    $local_fs $remote_fs 
# Required-Stop:     $local_fs $remote_fs 
# X-Start-Before:    $syslog apache2
# X-Stop-After:      $syslog apache2
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop tmpfs logfile saving
### END INIT INFO
#
# varlog        This init.d script is used to start tmpfs logfile saving and restore.
#

VERSION="0.7 (21.03.2023)"
VARLOGCONFIG=/etc/varlog.conf
TMPFSSIZE=70M
VARLOGSAVEDIR=/var/save.log
VERBOSE=0
RSPARAM="-a"
CPPARAM="-Rpu"
PATH=/sbin:/usr/sbin:/bin:/usr/bin
FORCESTOP=1
LOGFILE=/var/varlog.log
RSYNCLOGFILE=""
DATEFORMAT="%x %X"
LOG=0

### FUNCTION DEFS ###                                                     

function _log() {
	if [  $LOG -gt 0 ]; then
		D=$(date "+${DATEFORMAT}")
		echo -e "$D $1" | tee -a "${LOGFILE}"
	else
		echo -e "$1"
	fi
}

function _save() {
	if [ $VERBOSE -gt 0 ]; then
		_log "Starting to save /var/log into ${VARLOGSAVEDIR}" 
	fi
	if [ -x "$(which rsync)" ]; then
		if [ $VERBOSE -gt 0 ]; then
			_log "Using rsync command"
		fi
		rsync $RSPARAM --delete /var/log/ ${VARLOGSAVEDIR}
	else
		if [ $VERBOSE -gt 0 ]; then
			_log "Using cp command"
		fi
		cp $CPPARAM /var/log/* ${VARLOGSAVEDIR}/  | tee -a "${LOGFILE}"
	fi
	sync
	if [ $VERBOSE -gt 0 ]; then
		_log "Finished to save /var/log"
	fi
}

function _restore() {
	if [ $VERBOSE -gt 0 ]; then
		_log "Starting to restore /var/log from ${VARLOGSAVEDIR}" 
	fi
	if [ -x "$(which rsync)" ]; then
		if [ $VERBOSE -gt 0 ]; then
			_log "Using rsync command" 
		fi
		rsync $RSPARAM -u --delete ${VARLOGSAVEDIR}/ /var/log
	else
		if [ $VERBOSE -gt 0 ]; then
			_log "Using cp command"
		fi
		cp $CPPARAM ${VARLOGSAVEDIR}/* /var/log/  | tee -a "${LOGFILE}"
	fi
	sync
	if [ $VERBOSE -gt 0 ]; then
		_log "Finished to restore /var/log"
	fi                                                                                
}

function _start() {
	_log "Starting tmpfs file restore: varlog."
	if [ -z "$(grep /var/log /proc/mounts)" ]; then
		_save
		#varlogsize=$(grep /var/log /etc/fstab|awk {'print $4'}|cut -d"=" -f2)
		 varlogsize=$(grep -oE "/var/log.+size=[0-9]+[MmGgKk]" /etc/fstab | grep -oE "[0-9]+[MmGgKk]$")
		[ -z "${varlogsize}" ] && varlogsize=$TMPFSSIZE
		if [ $VERBOSE -gt 0 ]; then
			_log "Size of tmpfs: ${varlogsize}" 
		fi
		_log "mounting /var/log .."
		mount -t tmpfs tmpfs /var/log -o defaults,size=$varlogsize
		chmod 775 /var/log
		_restore
	else
		_log "/var/log already mounted as tmpfs!"
		if [ -n "$1" ]; then
			_log "forcing restore from ${VARLOGSAVEDIR}"
			_restore
		fi
	fi	
}

function _stop() {
	if [ -z "$(grep /var/log /proc/mounts)" ]; then
		_log "/var/log already unmounted. nothing to do."
	else
		sync -f /var/log/kern.log
		_log "Stopping tmpfs file saving: varlog."
		_save
		_log "unmounting /var/log .."
		umount -f /var/log/
		if [ -z "$(grep /var/log /proc/mounts)" ]; then
			_log "/var/log unmounted successfully"
			_restore
		else
			_log "ERROR: /var/log still mounted!"
			if [ $1 -gt 0 ]; then
				_log "Try to unmount lazy."
				umount -l /var/log/
				if [ -z "$(grep /var/log /proc/mounts)" ]; then
					_log "/var/log unmounted successfully FINALLY!"
					_restore
				else
					_log "/var/log STILL mounted! This should not happen!"
				fi
			fi
		fi
	fi
}

function _stop_apache2() {
	if [ $VERBOSE -gt 0 ]; then
		_log "Checking if apache2 is running..."
	fi
	APACHE2STATUS=$(service apache2 status)
	if [[ $APACHE2STATUS == *"Active: active (running)"* ]]; then
		_log "Apache2 is RUNNING! Stopping.."
		APACHE2=1
		service apache2 graceful-stop
	elif [[ $APACHE2STATUS == *"Active: failed"* ]]; then
		_log "Apache2 failed but stopping it.."
		APACHE2=1
		service apache2 stop
	else
		if [ $VERBOSE -gt 0 ]; then
			_log "Apache2 is not running."
		fi
	fi
}

function _start_apache2() {
	if [ $APACHE2 > 0 ]; then
		_log "Restarting Apache2..."
		service apache2 start
	else
		if [ $VERBOSE -gt 0 ]; then
			_log "Apache2 was not running previously. Nothing to do." 
		fi
	fi
}

### MAIN CODE STARTS HERE ###

if [ $(id -u) -ne 0 ]; then
	echo -e "Script must be run as root. Try 'sudo $0'\n"
	exit 1
fi

if [ "$1" == "-v" ]; then
	VERBOSE=1
	shift
fi

if [ "$2" == "-v" ]; then
	VERBOSE=1	
fi

if [ -x $VARLOGCONFIG ]; then
	source $VARLOGCONFIG

	if [ $VERBOSE -gt 0 ]; then
		_log "Using config file ${VARLOGCONFIG}";
	fi
fi

if [ ! -d $VARLOGSAVEDIR ]; then
	if [ $VERBOSE -gt 0 ]; then
		_log "Varlog save dir does not exist!\nCreating ${VARLOGSAVEDIR} .." 
	fi
	mkdir -p $VARLOGSAVEDIR
fi

if [ $VERBOSE -gt 0 ]; then
	RSPARAM="-va"
	CPPARAM="-vRpu"
fi

if [  $LOG -gt 0 ]; then
	if [ ! -z "$RSYNCLOGFILE" ]; then
		RSPARAM="${RSPARAM} --log-file=${RSYNCLOGFILE}"
	fi
fi

APACHE2=0

if [ ! -d "$VARLOGSAVEDIR" ]; then
	if [ $VERBOSE -gt 0 ]; then
		_log "${VARLOGSAVEDIR} does not exist. Creating..."
	fi
	mkdir -p $VARLOGSAVEDIR
	if [ ! -d "$VARLOGSAVEDIR" ]; then
		_log "ERROR: Could not create ${VARLOGSAVEDIR} !"
		exit 1
	else
		if [ $VERBOSE -gt 0 ]; then
			_log "${VARLOGSAVEDIR} created successfully." 
		fi
	fi
fi

case $1 in
	start)
		_stop_apache2
		_start ""
		_start_apache2
	;;
	forcestart)
		_stop_apache2
		_start "force"	
		_start_apache2
	;;
	stop)
		_stop_apache2
		_stop ${FORCESTOP}
		_start_apache2
	;;
	forcestop)
		_stop_apache2
		_stop 1
		_start_apache2
	;;
	status)
		if [ $VERBOSE -gt 0 ]; then
			echo "Path to save log into is ${VARLOGSAVEDIR}";
			echo "TMPFS Size is set to ${TMPFSSIZE}";
			if [ $FORCESTOP -gt 0 ]; then
				echo "FORCESTOP is set true. Will try to lazy unmount if necessary..";
			fi
		fi
		if [ -z "$(grep /var/log /proc/mounts)" ]; then
			echo "/var/log is NOT mounted as tmpfs!"
		else
			echo "/var/log seems to be mounted as tmpfs!"
		fi		
	;;
	version)
		echo "Varlog Version is ${VERSION}"
	;;
	*)
		echo "Usage: $0 {start|stop|status|forcestart|forcestop|version}"
		exit 1
	;;
esac


exit 0
